global:
  resolve_timeout: 1m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
  
receivers:
- name: 'email'
  email_configs:
  - to: 'roberta.gabriela0619@gmail.com'
    from: 'roberta.gabriela0619@gmail.com'
    smarthost: smtp.gmail.com:587
    auth_username: 'roberta.gabriela0619@gmail.com'
    auth_identity: 'roberta.gabriela0619@gmail.com'
    auth_password: 'ffuizbgmdaaupjhc'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']